### ISSUE TITLE
Draw popup before starting the game

### ISSUE THREAD

**Issue by serj99** [Vel1khan/pixel-chess#1]
After pressing the 'Play now!' button this is happening:  
![Screenshot_2021-02-14 Pixel Chess](https://user-images.githubusercontent.com/1117393/107875051-55fa9e80-6ec6-11eb-893b-50d96416f1e6.png)

So I'm pushing 'Okay' just wondering what will be next. Without any move in the game and the program makes me dumb! 

![Screenshot_2021-02-14 Pixel Chess(1)](https://user-images.githubusercontent.com/1117393/107875147-e20cc600-6ec6-11eb-875d-36617bda86d5.png)

**Comment by Zaheudev** [comment]
I know, this is temporary

**Comment by Vel1khan** [comment]
Thanks for the heads up, the project is still a work in progress so we have not hashed everything out yet, we'll resolve it in the near future.

**Comment by Vel1khan** [comment]
Fixed,the only reason the pop-ups showed up was for debugging, they had no effect on the actual game itself. Now that we're happy with how the pop-ups work, we removed it. Feel free to check it out now.

Commit: ede589bbdb84bdd8f887f3255772c37f8f3fc415
